# Service account the client will use to reset the deployment,
# by default the pods running inside the cluster can do no such things.
kind: ServiceAccount
apiVersion: v1
metadata:
  name: github
---
# bind the role to the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    namespace: default
    name: github
---
apiVersion: v1
kind: Secret
metadata:
  name: github-token
  annotations:
    kubernetes.io/service-account.name: github
type: kubernetes.io/service-account-token
