apiVersion: batch/v1
kind: CronJob
metadata:
  name: ddclient
spec:
  concurrencyPolicy: Forbid
  schedule: '@hourly'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ddclient-cloudflare
            image: ghcr.io/marizmendi/ddclient:latest
            env:
            - name: DDCLIENT_LOGIN
              value: manmar92@gmail.com
            - name: DDCLIENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudflare
                  key: global_api_key
            - name: HOST
              value: arizxyz.com
            command:
            - /bin/sh
            - -c
            - mkdir /etc/ddclient/; envsubst < "/tmp/ddclient/cloudflare.conf.template" > "/etc/ddclient/ddclient.conf"; /bin/ddclient --cache /var/cache/ddclient.cache
            volumeMounts:
            - mountPath: /tmp/ddclient
              name: ddclient
          - name: ddclient-namecheap
            image: ghcr.io/marizmendi/ddclient:latest
            env:
            - name: DDCLIENT_LOGIN
              value: ariz.xyz
            - name: DDCLIENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: namecheap
                  key: password
            - name: HOST
              value: boston
            command:
            - /bin/sh
            - -c
            - mkdir /etc/ddclient/; envsubst < "/tmp/ddclient/namecheap.conf.template" > "/etc/ddclient/ddclient.conf"; /bin/ddclient --cache /var/cache/ddclient.cache
            volumeMounts:
            - mountPath: /tmp/ddclient
              name: ddclient
          volumes:
            - name: ddclient
              configMap:
                name: ddclient
          restartPolicy: OnFailure
