apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: wireguard
  name: wireguard
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 5555
    nodePort: 32323
    protocol: UDP
    targetPort: 5555
  selector:
    app: wireguard
