apiVersion: v1
kind: ConfigMap
metadata:
  name: ddclient
data:
  cloudflare.conf.template: |
    use=web, web=dynamicdns.park-your-domain.com/getip
    ssl=yes

    protocol=cloudflare
    login=$DDCLIENT_LOGIN
    password=$DDCLIENT_PASSWORD
    zone=$HOST
    $HOST, www.$HOST

  namecheap.conf.template: |
    use=web, web=dynamicdns.park-your-domain.com/getip
    ssl=yes

    protocol=namecheap
    login=$DDCLIENT_LOGIN
    password=$DDCLIENT_PASSWORD
    $HOST
